export { default as HomeScreen2 } from './home-screen/HomeScreen2';
export { default as Login } from './login/Login';
export { default as StarRating } from './star-rating/StarRating';
export { default as Settings } from './setting/Settings';
export { default as WebrtcHome } from './home-screen/HomeScreen';
export { default as DuringCall } from './during-call/DuringCall';
export { default as DuringCall2 } from './during-call/DuringCall2';
export { default as ChatScreen } from './chat-screen/ChatScreen';
export { default as Call } from './during-call/Call';